### GET All Movies ###
GET http://localhost:3000/movies


### GET Single Movie ###
GET http://localhost:3000/movies/65cea088f940a690598b5835
### GET Single Movie ###
GET http://localhost:3000/movies/65cea088f940a690598b5835
### GET Single Movie ###
GET http://localhost:3000/movies/65cea088f940a690598b5836
### GET Single Movie ###
GET http://localhost:3000/movies/65cea088f940a690598b5837

### Create movie
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
   "title": "Interstellar",
    "genre": "Science Fiction",
    "director": "Christopher Noland",
    "year": 2014,
    "rating": "PG-13"
}


### PUT Movie ###
PUT http://localhost:3000/movies/65c7bafc7545626e519d8506 HTTP/1.1
Content-Type: application/json

{
    "title": "Interstellar",
    "genre": "Science Fiction",
    "director": "Christopher Nolan",
    "year": 2014,
    "rating": "PG-13"
}

### DELETE Movie ###
DELETE http://localhost:3000/movies/65cea0da7b13d1a9ab2b089e HTTP/1.1



// PRODUCTION Deploy
### GET All Movies ###
GET https://cse341-winter24-uqt1.onrender.com/movies

### POST New Movie ###
POST https://cse341-winter24-uqt1.onrender.com/movies
Content-Type: application/json

{
    "title": "Interstellar",
    "genre": "Science Fiction",
    "director": "Christopher Nolan",
    "year": 2014,
    "rating": "PG-13"
}

### GET Single Movie ###
GET https://cse341-winter24-uqt1.onrender.com/movies/65c48e75f940a690598b582a
### GET Single Movie ###
GET https://cse341-winter24-uqt1.onrender.com/movies/65c48e75f940a690598b582b
### GET Single Movie ###
GET https://cse341-winter24-uqt1.onrender.com/movies/65c48e75f940a690598b582c
### GET Single Movie ###
GET https://cse341-winter24-uqt1.onrender.com/movies/65c48e75f940a690598b582d

### Create movie
POST https://cse341-winter24-uqt1.onrender.com/movies HTTP/1.1
content-type: application/json

{
   "title": "Interstellar",
    "genre": "Science Fiction",
    "director": "Christopher Noland",
    "year": 2014,
    "rating": "PG-13"
}


### PUT Movie ###
PUT https://cse341-winter24-uqt1.onrender.com/movies/65c7bafc7545626e519d8506 HTTP/1.1
Content-Type: application/json

{
    "title": "Interstellar",
    "genre": "Science Fiction",
    "director": "Christopher Nolan",
    "year": 2014,
    "rating": "PG-13"
}

### DELETE Movie ###
DELETE https://cse341-winter24-uqt1.onrender.com/movies/65c86290d2d77d47b3e1bd18 HTTP/1.1